---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    volumes:
      - code-server_config:/config
    ports:
      - 8443:8443
    env_file:
      - ./code-server/code-server.env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/etc/code-server.conf:/etc/nginx/conf.d/code-server.conf.template
      - /dev/null:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/code-server.conf.template > /etc/nginx/conf.d/code-server.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    env_file:
      - default.env
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/etc:/etc/nginx/conf.d
    env_file:
      - default.env
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  code-server_config: